apiVersion: v1
kind: Deployment
metadata:
  name: secret-service
  labels:
    app: secret-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-service
  template:
    metadata:
      labels:
        app: secret-service
    spec:
      containters:
      - image: docker.io/maciejprzybylo95/secret-service
        ports:
        - containerPort: 3000
