apiVersion: v1
kind: Deployment
metadata:
  name: aes-encyption-service
  labels:
    app: aes-encyption-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aes-encyption-service
  template:
    metadata:
      labels:
        app: aes-encyption-service
    spec:
      containters:
      - image: docker.io/maciejprzybylo95/aes-encyption-service
        ports:
        - containerPort: 3000
