apiVersion: v1
kind: Deployment
metadata:
  name: session-token-service
  labels:
    app: session-token-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-token-service
  template:
    metadata:
      labels:
        app: session-token-service
    spec:
      containters:
      - image: docker.io/maciejprzybylo95/session-token-service
        ports:
        - containerPort: 3000
