apiVersion: v1
kind: Deployment
metadata:
  name: authentification-service
  labels:
    app: authentification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentification-service
  template:
    metadata:
      labels:
        app: authentification-service
    spec:
      containters:
      - image: docker.io/maciejprzybylo95/authentification-service
        ports:
        - containerPort: 3000
        env:
        - name: ACTIVATION_LINK
          value: http://35.240.33.72/authentication/api/activate
