apiVersion: v1
kind: Deployment
metadata:
  name: mongo-service
  labels:
    app: mongo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-service
  template:
    metadata:
      labels:
        app: mongo-service
    spec:
      containters:
      - image: docker.io/maciejprzybylo95/mongo-service
        ports:
        - containerPort:
